[package]
name = "evolisa"
version = "0.1.0"
authors = ["planet0104 <planet0104@gmail.com>"]

[dependencies]
rand = "*"
image = "0.19.0"
imageproc = "0.15.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link", "gfx"]

[profile.release]
lto = true
panic = 'abort'